repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-black
      args: ["src/", "unit_tests/"]
    - id: check-commit-message
      stages: [commit-msg]
